### ISSUE TITLE
Créer page github

### ISSUE THREAD

**Issue by YoannDupont** [Jon-a-tanne/Depot_DEPENDANCE#1]
Bonjour,

Vous semblez avoir des pages disponibles dans votre dossier [Site_Jonathan](https://github.com/Jon-a-tanne/Depot_DEPENDANCE/tree/main/HTML%20%26%20CSS/Site_Jonathan). Seulement, vous ne semblez pas avoir une page Github disponible.

Il faudrait, au choix :

- idéalement, réorganiser le dépôt pour que le contenu de [Site_Jonathan](https://github.com/Jon-a-tanne/Depot_DEPENDANCE/tree/main/HTML%20%26%20CSS/Site_Jonathan) se retrouve à la racine.
- créer un fichier `index.html` à la racine, quitte à ce qu'il serve principalement à donner un lien vers `Site_Jonathan`

Cordialement.

**Comment by Jon-a-tanne** [comment]
Création de la page Github et update du dépot.
